---
name: Pull Request
on:   [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 500

      - name: Run Luacheck
        uses: meorawr/actions-luacheck@feature/annotations
        with:
          args: "--no-color -q"
